version: "3"

volumes:
  static_files:

services:
  db:
    image: postgres

  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py loaddata villafleurie.json && gunicorn -w 4 villafleurie.wsgi -b 0.0.0.0:8000"
    # container_name: villafleurie
    volumes:
      - .:/villafleurie
      - static_files:/static_files
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: prod.env

  nginx:
    # image: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - static_files:/static_files
    depends_on:
      - web
