# Generated by Django 2.2.6 on 2019-11-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='decription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='place',
            name='subname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
