# Generated by Django 2.2.6 on 2019-11-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_auto_20191107_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='info',
            field=models.TextField(blank=True),
        ),
    ]
