# Generated by Django 2.2.6 on 2019-11-07 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_auto_20191107_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rental.Reservation'),
        ),
    ]
