# Generated by Django 2.2.6 on 2019-11-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_auto_20191107_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
