# Generated by Django 2.2.6 on 2019-11-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0009_auto_20191107_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
