# Generated by Django 2.2.6 on 2019-11-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0010_auto_20191107_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
