# Generated by Django 2.2.6 on 2019-11-10 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0011_auto_20191107_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('alt', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='place',
            name='pictures',
        ),
        migrations.AddField(
            model_name='place',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rental.Image'),
        ),
    ]
