# Generated by Django 2.2.6 on 2019-11-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0013_auto_20191110_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='place',
        ),
        migrations.AddField(
            model_name='image',
            name='place',
            field=models.ManyToManyField(blank=True, null=True, to='rental.Place'),
        ),
    ]
