# Generated by Django 2.2.6 on 2019-11-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0014_auto_20191110_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='place',
            field=models.ManyToManyField(blank=True, related_name='images', to='rental.Place'),
        ),
    ]
