# Generated by Django 2.2.6 on 2019-11-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0015_auto_20191110_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img',
            new_name='url',
        ),
    ]
