# Generated by Django 2.2.6 on 2019-11-11 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0016_auto_20191110_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='place',
        ),
        migrations.AddField(
            model_name='place',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='places', to='rental.Image'),
        ),
        migrations.AddField(
            model_name='place',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rental.Image'),
        ),
    ]
