# Generated by Django 2.2.6 on 2019-11-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0017_auto_20191111_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='url',
            new_name='img',
        ),
        migrations.AlterField(
            model_name='place',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='places', to='rental.Image'),
        ),
    ]
