# Generated by Django 2.2.6 on 2019-11-11 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0019_auto_20191111_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='end',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='start',
        ),
    ]
