# Generated by Django 2.2.6 on 2019-11-11 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0021_auto_20191111_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.Place'),
        ),
    ]
