# Generated by Django 2.2.7 on 2019-12-03 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0023_reservation_quotation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='quotation',
            new_name='price',
        ),
    ]
