# Generated by Django 3.0 on 2019-12-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0025_auto_20191206_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='calendar',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
