# Generated by Django 3.0.4 on 2020-03-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0029_auto_20200331_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='picture',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
